// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Book struct {
	ID           int64
	Title        string
	Author       string
	Publishdate  sql.NullTime
	Pagecount    sql.NullInt64
	Readstatus   sql.NullInt64
	CollectionID sql.NullInt64
}

type BookGenre struct {
	BookID  sql.NullInt64
	GenreID sql.NullInt64
}

type Collection struct {
	ID    int64
	Title string
}

type Genre struct {
	ID   int64
	Name string
}
